task:
  name: cocoqa
  #debug: 1024

model:
  name: nmn
  lstm_hidden: 500
  att_hidden: 200
  pred_hidden: 200

opt:
  batch_size: 100
  iters: 1001

  rho: 0.95
  eps: 0.000001
  lr: 1
  clip: 10.0
