task:
  name: vqa
  #debug: 1013
  multi: true
  cvpr_chooser: false
  null_chooser: false
  measure: false

model:
  name: nmn
  lstm_hidden: 1000
  layout_hidden: 100
  att_hidden: 100
  pred_hidden: 500
  
  ##lstm_hidden: 1000
  #layout_hidden: 100
  #att_hidden: 100
  #pred_hidden: 500

     # don't forget scale!

opt:
  batch_size: 100
  iters: 20

  rho: 0.95
  eps: 0.000001
  lr: 1
  clip: 10.0
