task:
  name: vqa
  #debug: 1013

  multi: false
  measure: false

model:
  name: att
  lstm_hidden: 500
  att_hidden: 100

opt:
  batch_size: 100
  iters: 30

  rho: 0.95
  eps: 0.000001
  lr: 1
  clip: 10.0
